import { createClient } from '@/lib/supabase/server'
import { getSessionId } from '@/lib/session'
import { getPosterUrl } from '@/lib/tmdb'
import { RecommendationsTabs } from '@/components/recommendations-tabs'
import { Header } from '@/components/header'
import { Button } from '@/components/ui/button'
import Link from 'next/link'
import { redirect } from 'next/navigation'
import { Metadata } from 'next'
import { THRESHOLDS } from '@/lib/constants'

export const metadata: Metadata = {
  title: 'Your Watch List | AI-Powered Recommendations',
  description: 'View your personalized movie and TV show recommendations generated by AI based on your unique taste.',
}

export default async function RecommendationsPage() {
  const sessionId = await getSessionId()
  
  if (!sessionId) {
    redirect('/onboarding')
  }

  const supabase = await createClient()

  // Get all recommendations with feedback
  const { data: recs } = await supabase
    .from('recommendations')
    .select(`
      *,
      movie_feedback (status, rating, reason)
    `)
    .eq('session_id', sessionId)
    .order('created_at', { ascending: false })
  
  // Fetch TMDB details in parallel with error handling
  const TMDB_KEY = process.env.TMDB_API_KEY
  
  const detailsPromises = (recs || []).map(async (rec) => {
    const isTV = rec.media_type === 'tv'
    const tmdbId = isTV ? rec.tmdb_tv_id : rec.tmdb_movie_id
    
    if (!tmdbId || !TMDB_KEY) return null
    
    try {
      const endpoint = isTV ? 'tv' : 'movie'
      const res = await fetch(
        `https://api.themoviedb.org/3/${endpoint}/${tmdbId}?append_to_response=credits`,
        { 
          headers: { Authorization: `Bearer ${TMDB_KEY}` },
          next: { revalidate: 3600 } // Cache for 1 hour
        }
      )
      return res.ok ? res.json() : null
    } catch (e) {
      console.error('Error fetching details:', e)
      return null
    }
  })
  
  // Batch fetch all details
  const details = await Promise.allSettled(detailsPromises)
  
  const recsWithDetails = (recs || []).map((rec, index) => ({
    ...rec,
    movieDetails: details[index].status === 'fulfilled' ? details[index].value : null
  }))

  if (!recs || recs.length === 0) {
    redirect('/onboarding')
  }

  // Transform data
  const recsWithFeedback = recsWithDetails.map(rec => ({
    ...rec,
    posterUrl: getPosterUrl(rec.poster_path),
    feedback: rec.movie_feedback?.[0] || null
  }))

  // Count watched & rated movies
  const ratedCount = recsWithFeedback.filter(
    r => r.feedback?.status === 'watched' && r.feedback?.rating
  ).length

  // Check if user is authenticated
  const { data: { user } } = await supabase.auth.getUser()

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <div className="max-w-7xl mx-auto px-4 py-12">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
          <div>
            <h1 className="text-4xl md:text-5xl font-bold mb-3">Your Watch List</h1>
            <p className="text-lg text-muted-foreground">
              {ratedCount >= THRESHOLDS.MIN_RATINGS_FOR_MORE 
                ? `${ratedCount} titles rated - you can load more!`
                : `Rate ${THRESHOLDS.MIN_RATINGS_FOR_MORE - ratedCount} more to unlock new recommendations`
              }
            </p>
          </div>
          
          {!user && (
            <Button asChild size="lg">
              <Link href="/auth/sign-up">Save Progress (Sign Up)</Link>
            </Button>
          )}
        </div>

        <RecommendationsTabs 
          recommendations={recsWithFeedback}
          ratedCount={ratedCount}
        />

        <div className="mt-12 text-center space-x-4">
          <Button variant="outline" asChild>
            <Link href="/onboarding">Start Over</Link>
          </Button>
          {user && (
            <Button variant="outline" asChild>
              <Link href="/protected">Go to Dashboard</Link>
            </Button>
          )}
        </div>
      </div>
    </div>
  )
}

